settings_version: 0.0.4
datasets_dir: /app/datasets
weights_dir: weights
runs_dir: runs
uuid: 5aa72cb2f1054b748bca075f0fedb7c705f6121995e2647e086dd1de876d84a3
sync: true
api_key: ''
openai_api_key: ''
clearml: true
comet: true
dvc: true
hub: true
mlflow: true
neptune: true
raytune: true
tensorboard: true
wandb: true
