version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"  # Change this to the desired host port
    environment:
      FLASK_APP: manage.py
      FLASK_RUN_HOST: 0.0.0.0
    volumes:
      - .:/app
